name: Docker Image CI

on:
  push:
    branches:
      - "main"
      - "develop"

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Build the Docker image
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          docker build . --file Dockerfile --tag ghcr.io/helios-collabathon/dapp-frontend:mainnet
        elif [ "${{ github.ref_name }}" == "develop" ]; then
          docker build . --file Dockerfile --tag ghcr.io/helios-collabathon/dapp-frontend:devnet
        fi

    - name: Push the Docker image
      run: |
        if [ "${{ github.ref_name }}" == "main" ]; then
          docker push ghcr.io/helios-collabathon/dapp-frontend:mainnet
        elif [ "${{ github.ref_name }}" == "develop" ]; then
          docker push ghcr.io/helios-collabathon/dapp-frontend:devnet